# Generated by Django 4.2.7 on 2023-11-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Enter a valid email address."},
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(
                error_messages={"unique": "Contact with this name already exists."},
                max_length=20,
                unique=True,
            ),
        ),
    ]
